### ISSUE TITLE
Support Conditional Comments

### ISSUE THREAD

**Issue by jescalan** [reshape/sugarml#14]
### Proposed Syntax

sgr:

``` jade
// regular comment
//[if IE 7]
  p some content
```

html:

``` html
<!-- regular comment -->
<!--[if IE 7]>
  <p>some content</p>
<![endif]-->
```
### Proposed Implementation

These tags are tricky because they can contain nested content. As such, they need their own type, and cannot be a modification to the normal comment type. This means it will also include an update to the code-gen.

The lexer should create a `conditionalComment` tag, which the parser would treat with a little recursing loop just about the same as tags are handled now. The code generator would need a little custom logic to format the open and close tags correctly, but again much of the logic can be borrowed from how tags are treated, since the way its rendered isn't really any different.

**Comment by Elbone** [comment]
Is there a workaround for this that you know of @jescalan?
I've tried prepending with a pipe but the comment seems to be reformatted.

**Comment by jescalan** [comment]
Oh, yeah we just shipped a fix for this. Upgrade to the latest version of reshape and it will work by default 🙌
