### ISSUE TITLE
Throw syntax error when trailing period is found

### ISSUE THREAD

**Issue by hhsnopek** [reshape/sugarml#27]
```
// throws error
li.category.
  h2 {{ slugName }} 

// does not throw error
li.category. foo
  h2 {{ slugName }} 
```

When using variables, an error is thrown that `slugName` is undefined, but the error is valid though it's not caused by the variable name itself, but a syntax error in the parent.

**Comment by jescalan** [comment]
Oh thats not a syntax error, thats block content, this is exactly how it's supposed to behave:

https://github.com/reshape/sugarml#text-block-content

**Comment by hhsnopek** [comment]
it throws an error stating `slugName` is undefined when really it's a syntax error that's causing the issue and the content is properly nested. This shouldn't be the behavior in this case as `slugName` isn't the cause of the problem.

**Comment by jescalan** [comment]
If it's throwing an error saying `slugName` is undefined, that's an issue with `reshape-expressions` I think...
