### ISSUE TITLE
Trailing whitespace after class name problem

### ISSUE THREAD

**Issue by tmpfs** [reshape/sugarml#30]
It appears to me that if there is trailing whitespace at the end of a class name the generated HTML nesting is not correct.

For example if I have:

```
ul.info 
  li Item
```

Noting that the class name `info` is followed by a single space character, I end up with markup like:

```
<ul class="info "></ul>
<li>Item</li>
```

I think in this instance that `sugarml` could deal with this more gracefully, it took me a little bit of head scratching to work out why the nesting was wrong ;)

I also don't recall ever running into this issue with `jade` which I believe this standard plugin has borrowed from.

Thanks for reshape - really enjoying it so far :)

Note: moved from https://github.com/reshape/standard/issues/12.

**Comment by tmpfs** [comment]
Note that this is not specific to class names, it appears to be any trailing whitespace.

I just hit this issue again converting:

```
h2 Title
```

To:

```
h2 
  span Title
```

If I forget to delete the space between the tag and the text before breaking the line the same problem occurs.

**Comment by jescalan** [comment]
Will take a look at this today. In the meantime, I'd strongly recommend installing the [editorconfig plugin](http://editorconfig.org/#download) for your text editor, which will greatly help in eliminating excess whitespace issues!
