### ISSUE TITLE
A small regression

### ISSUE THREAD

**Issue by jescalan** [reshape/sugarml#32]
Fixing the last colon issue introduced a new one, sadly:

```
.foo: p.bar
```

now renders as:

```
<div class='foo'>
  <p>
    <div class='bar'></div>
  </p>
</div>
```

**Comment by adamkiss** [comment]
@jescalan I've ran into this few times, and now that I forked, I could looked into to; do ou have any references where to start? Thanks

**Comment by jescalan** [comment]
https://github.com/reshape/sugarml/blob/master/lib/lexer.js#L316
