### ISSUE TITLE
Conditional Comment Rendering

### ISSUE THREAD

**Issue by tortilaman** [reshape/sugarml#42]
I think it would be really handy to have the ability to include coments in your raw sugarml that aren't compiled into the html. There are definitely times where documentation is useful for developers, but even on a dev server doesn't make any sense to be included. This is currently implemented in Pug / Jade and I think would be a great addition

# Proposed Syntax
### Sugarml
```sugarml
// Regular Comment

//- Not rendered in markup
```
### HTML
```html
// Regular Comment
```

**Comment by jescalan** [comment]
I agree, this is a great idea! It also is a fairly simple implementation, and would be a good place to contribute. Are you interested in this at all?

**Comment by tortilaman** [comment]
Sure, I'll see if I can figure it out.
