### ISSUE TITLE
No support/documentation for multiple-line preformatted text

### ISSUE THREAD

**Issue by Standard8** [reshape/sugarml#48]
I'm trying to use preformatted text over multiple lines, but I can't find a way to do it.

`pre line1\nline2` just ends up with `<pre>line1\nline2</pre>`
```
pre
  | line1
  | line2
```

ends up with

```
<pre>
  line1
</pre>
<pre>
  line2
</pre>
```

I'd like to end up with:

```
<pre>
  line1
  line2
</pre>
```

Is there an undocumented way to do this, or is this an issue sugarml itself?

**Comment by jescalan** [comment]
Even better, there's a documented way to do it!

https://github.com/reshape/sugarml#text-block-content

**Comment by Standard8** [comment]
I hadn't noticed that. Thanks!
